title: "ancailliau's brain dump"
author: "Antoine Cailliau"
description: "My brain dump." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

twitter_username: "ancailliau"
github_username: "ancailliau"
linkedin_username: "ancailliau"

show_excerpts: true

header_pages:
  - /k8s/

theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
