title: "ancailliau's brain dump"
author:
  name: "Antoine Cailliau"
  twitter: ancailliau
  linkedin: ancailliau
tagline: "Antoine Cailliau's brain dump | bits and bytes about computers and cybersecurity"
description: "Antoine Cailliau's brain dump, bits and bytes about computers and cybersecurity"
url: https://ancailliau.github.io/

google_site_verification: "KNazH1EP7iwZpFNn0TrpOxDew_UskQwI6YZCYbDN6TQ"
  
twitter_username: "ancailliau"
github_username: "ancailliau"
linkedin_username: "ancailliau"

show_excerpts: true
paginate: 5

header_pages:
  - /k8s/

theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
